
# name: Release Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   run-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run Tests
#         run: $GITHUB_WORKSPACE/run-tests.yaml

#   deploy-code:
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Deploy Code
#         run: $GITHUB_WORKSPACE/run-tests.yaml
